In [2]:
import pandas as pd
import matplotlib as plt

In [3]:
df=pd.read_csv("C:\\Users\\badat\\Downloads\\archive.zip")

In [3]:
df.head(6)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly
5,3583,23,Female,Shorts,Clothing,41.0,California,S,Beige,Summer,3.4,No,2-Day Shipping,No,15.0,PayPal,Annually

In [5]:
df.isnull().sum()

Customer ID                 0
Age                         0
Gender                      0
Item Purchased              0
Category                    0
Purchase Amount (USD)     556
Location                    0
Size                      370
Color                       0
Season                      0
Review Rating             601
Subscription Status         0
Shipping Type               0
Discount Applied            0
Previous Purchases        548
Payment Method              0
Frequency of Purchases      0
dtype: int64

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,5050.000000,5050.000000,4494.000000,4449.000000,4502.000000
mean,2519.570891,44.150495,144.765236,3.668195,25.221901
std,1470.402964,15.282328,275.590101,0.865357,14.521635
min,1.000000,18.000000,10.120000,1.000000,0.000000
25%,1252.250000,31.000000,41.000000,3.000000,13.000000
50%,2499.500000,44.000000,65.000000,3.700000,25.000000
75%,3740.750000,57.000000,89.000000,4.400000,38.000000
max,5099.000000,70.000000,1499.760000,5.000000,50.000000

In [6]:
df["Item Purchased"].unique()

array(['T-shirt', 'Sunglasses', 'Shirt', 'Gloves', 'Jewelry', 'Shorts',
       'Hat', 'Handbag', 'Shoes', 'Coat', 'Laptop', 'Hoodie', 'Phone',
       'Jacket', 'Pants', 'Backpack', 'Socks', 'Jeans', 'Bag', 'Belt',
       'Watch', 'Headphones', 'Blouse', 'Sandals', 'Skirt', 'Sweater',
       'Scarf', 'Sneakers', 'Boots', 'Dress'], dtype=object)

In [7]:
df["Category"].unique()

array(['Clothing', 'Accessories', 'Outerwear', 'Electronics', 'Footwear'],
      dtype=object)

In [8]:
df.groupby("Category")["Item Purchased"].unique()

Category
Accessories    [Sunglasses, Gloves, Jewelry, Hat, Handbag, Ph...
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone,...
Electronics    [Laptop, Phone, Watch, Bag, Shoes, Shirt, Head...
Footwear                       [Shoes, Sandals, Sneakers, Boots]
Outerwear                                         [Coat, Jacket]
Name: Item Purchased, dtype: object

In [9]:
pd.set_option('display.max_colwidth',None)
pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [10]:
df.groupby("Category")["Item Purchased"].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [11]:
df.groupby("Category")["Item Purchased"].unique()

Category
Accessories               [Sunglasses, Gloves, Jewelry, Hat, Handbag, Phone, Backpack, Belt, Bag, Headphones, Scarf, Watch, Shirt, Shoes, Laptop]
Clothing       [T-shirt, Shirt, Shorts, Shoes, Hoodie, Phone, Pants, Socks, Jeans, Bag, Blouse, Skirt, Sweater, Watch, Laptop, Dress, Headphones]
Electronics                                                                                 [Laptop, Phone, Watch, Bag, Shoes, Shirt, Headphones]
Footwear                                                                                                        [Shoes, Sandals, Sneakers, Boots]
Outerwear                                                                                                                          [Coat, Jacket]
Name: Item Purchased, dtype: object

In [4]:
correct_mapping = {
    # Clothing
    "T-shirt": "Clothing","Shirt":"Clothing","Shorts":"Clothing",
    "Hoodie":"Clothing","Pants":"Clothing","Socks":"Clothing",
    "Jeans":"Clothing","Blouse":"Clothing","Skirt":"Clothing",
    "Sweater":"Clothing","Dress":"Clothing",
    
    # Accessories
    "Sunglasses":"Accessories","Gloves": "Accessories","Jewelry":"Accessories",
    "Hat":"Accessories", "Handbag":"Accessories","Backpack":"Accessories",
    "Belt":"Accessories","Bag": "Accessories","Scarf":"Accessories",
    
    # Electronics
    "Laptop":"Electronics","Watch":"Electronics","Headphones":"Electronics","Phone":"Electronics",
    
    # Footwear
    "Shoes":"Footwear","Sandals":"Footwear","Sneakers":"Footwear","Boots":"Footwear",
    
    # Outerwear
    "Coat":"Outerwear","Jacket":"Outerwear"}

In [5]:
correct_mapping

{'T-shirt': 'Clothing',
 'Shirt': 'Clothing',
 'Shorts': 'Clothing',
 'Hoodie': 'Clothing',
 'Pants': 'Clothing',
 'Socks': 'Clothing',
 'Jeans': 'Clothing',
 'Blouse': 'Clothing',
 'Skirt': 'Clothing',
 'Sweater': 'Clothing',
 'Dress': 'Clothing',
 'Sunglasses': 'Accessories',
 'Gloves': 'Accessories',
 'Jewelry': 'Accessories',
 'Hat': 'Accessories',
 'Handbag': 'Accessories',
 'Backpack': 'Accessories',
 'Belt': 'Accessories',
 'Bag': 'Accessories',
 'Scarf': 'Accessories',
 'Laptop': 'Electronics',
 'Watch': 'Electronics',
 'Headphones': 'Electronics',
 'Phone': 'Electronics',
 'Shoes': 'Footwear',
 'Sandals': 'Footwear',
 'Sneakers': 'Footwear',
 'Boots': 'Footwear',
 'Coat': 'Outerwear',
 'Jacket': 'Outerwear'}

In [14]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Previous Purchases,Payment Method,Frequency of Purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,M,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,L,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,L,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

In [6]:
df["Category"]=df["Item Purchased"].map(correct_mapping)

In [7]:
df['Category'].unique()

array(['Clothing', 'Accessories', 'Footwear', 'Outerwear', 'Electronics'],
      dtype=object)

In [23]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
df.groupby("Category")["Size"].unique()

Category
Accessories    [M, L, S, XL, nan]
Clothing       [XL, M, S, L, nan]
Electronics    [nan, L, S, M, XL]
Footwear       [M, L, S, nan, XL]
Outerwear           [XL, L, S, M]
Name: Size, dtype: object

In [16]:
#treating nullvalue or replace all values in the electonics category
df.loc[df['Category']=='Electronics','Size']="notapplicable"

In [17]:
#treating nullvalue or replace all values in the footwere category
df.loc[df['Category']=='Footwear','Size']="not avalable"

In [18]:
#treating nullvalue or replace all values in the Accessories  category
df.loc[df['Category']=='Accessories','Size']="al free"

In [19]:
#treating nullvalue or replace all values in the clothing  category
df.loc[(df["Category"]=="Clothing") & (df["Size"].isnull()),"Size"]=df[df["Category"]=="Clothing"]["Size"].mode()[0]

In [20]:
#fill null values nullvalue or replace all values in the review ratings
df["Review Rating"]=df["Review Rating"].fillna(df.groupby('Item Purchased')["Review Rating"].transform('mean'))

In [21]:
#filling Purchase Amount with (0)
df['Previous Purchases']=df['Previous Purchases'].fillna(0)

In [22]:
#fill null values nullvalue or replace all values in the 
df["Purchase Amount (USD)"]=df["Purchase Amount (USD)"].fillna(df.groupby('Item Purchased')["Purchase Amount (USD)"].transform('mean'))

### remove duplicate

In [20]:
df.duplicated().sum()

np.int64(50)

In [21]:
df=df.drop_duplicates(subset=['Customer ID'],keep='first')

In [22]:
len(df)

5000

### renaming the headers

In [23]:
df.columns

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Previous Purchases', 'Payment Method',
       'Frequency of Purchases'],
      dtype='object')

In [29]:
df.columns=df.columns.str.replace(" ","_")
df.columns=df.columns.str.lower()

In [25]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases'],
      dtype='object')

In [34]:
### rename purchase_amount_(usd) to purchase_amount
df=df.rename(columns={"purchase_amount_(usd)":" purchase_amount"})

In [32]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases
0,2701,22,Female,T-shirt,Clothing,68.0,California,XL,Olive,Winter,3.2,No,Standard,No,36.0,Cash,Weekly
1,521,51,Male,Sunglasses,Accessories,84.0,South Carolina,al free,White,Spring,3.9,Yes,Free Shipping,Yes,20.0,Debit Card,Quarterly
2,3157,18,Female,Shirt,Clothing,50.0,Montana,M,Black,Winter,3.1,No,2-Day Shipping,No,18.0,Cash,Monthly
3,1687,22,Male,Gloves,Accessories,75.0,Illinois,al free,Red,Fall,4.2,No,Store Pickup,No,25.0,Cash,Annually
4,2929,40,Female,Jewelry,Accessories,80.0,Alabama,al free,Yellow,Spring,3.6,No,Store Pickup,No,17.0,Credit Card,Weekly

#### conect to sql server

In [24]:
pip install pyodbc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyodbc in c:\programdata\anaconda3\lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

In [35]:
import pyodbc
from urllib.parse import quote_plus
from sqlalchemy import create_engine

driver = "ODBC Driver 17 for SQL Server"

connection_string = quote_plus(
    f"DRIVER={{{driver}}};"
    f"SERVER=localhost;"
    f"DATABASE=dataanalyst_analyst_project;"
    f"Trusted_Connection=yes;"
)

# create engine
engine = create_engine(f"mssql+pyodbc:///?odbc_connect={connection_string}")

print("successfully executed")

successfully executed

In [36]:
table_name="costumer_behaviour_analysis"
df.to_sql(table_name, engine, if_exists="replace", index=False)

7

In [37]:
table_name = "costumer_behaviour_analysis"
df.to_sql(table_name, engine, if_exists="replace", index=False)
print("sucsess")

sucsess